spring:
  application:
    name: runa-server

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    io.github.sboe0705: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30
